<a href="https://colab.research.google.com/github/Elwing-Chou/tibame_night_20251120/blob/main/tibame20251220.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import json
import urllib.request as req
import pandas as pd

url = "https://api.gamer.com.tw/anime/v1/danmu.php?videoSn=36632&geo=TW%2CHK"
f = req.urlopen(url)
content = f.read()
content = json.loads(content)

danmus = content["data"]["danmu"]
# pd: DataFrame表格 Series一列/一行
# json->dataframe
# [{}, {}, {}]
df = pd.DataFrame(danmus)
# 不要列標籤: index=False
df.to_csv("danmu.csv", encoding="utf-8")
df.to_excel("danmu.xlsx")
df

,text,color,size,position,time,sn,userid
0,二刷,#FFFFFF,1,0,0,42903755,qaz1210731
1,吉伊卡哇！,#FFFFFF,1,0,0,45641971,dodylee0107
2,感謝動畫瘋！,#FFFFFF,1,0,0,45796240,hyg125
3,2025.11.24簽,#FDE53D,1,0,0,47316552,MilkTea157
4,吉依好可愛,#FFFFFF,1,0,5,40580321,KingOrange69
...,...,...,...,...,...,...,...
524,ˊˊˊˊˊˊˊˊˊˊˊˊˊˊˊˊˊˊˊ,#FFFFFF,1,0,893,46704569,swyan
525,我,#FFFFFF,1,0,897,45779317,Webb2012
526,😀,#00C3FC,1,0,898,40894473,kekerry75
527,沒了？？？？,#FFFFFF,1,0,901,42188563,linzzi
528,哈,#FF0026,1,0,901,44529579,st5109185



```
1. 過濾: 準備跟你資料依樣多的True(保留)/False(刪去)
2. 轉換

```

In [9]:
testdf = df.head(3)
fil = [True, False, False]
testdf[fil]

  text    color  size  position  time        sn      userid
0   二刷  #FFFFFF     1         0     0  42903755  qaz1210731

In [11]:
# 1 col
df["text"]
# multiple cols
df[["userid", "text"]]

           userid                 text
0      qaz1210731                   二刷
1     dodylee0107                吉伊卡哇！
2          hyg125               感謝動畫瘋！
3      MilkTea157          2025.11.24簽
4    KingOrange69                吉依好可愛
..            ...                  ...
524         swyan  ˊˊˊˊˊˊˊˊˊˊˊˊˊˊˊˊˊˊˊ
525      Webb2012                    我
526     kekerry75                    😀
527        linzzi               沒了？？？？
528     st5109185                    哈

[529 rows x 2 columns]

In [ ]:
df["userid"].value_counts()

In [17]:
target = "tsubakilee"
fil = df["userid"] == target
df[fil]

                     text    color  size  position  time        sn      userid
157                 我第一次看  #FFFFFF     1         0   221  41164994  tsubakilee
172      有人在嗎嘉義\n\n有人在嗎+1  #FFFFFF     1         0   259  41165004  tsubakilee
342     有人跟我一樣晚上看嗎\n看了快餓死  #FFFFFF     1         0   576  41165019  tsubakilee
416  沒了？？？？？？？？？？？？？？？？？？  #FFFFFF     1         0   693  41165047  tsubakilee

In [20]:
# & and | or
fil1 = df["time"] >= 100
fil2 = df["time"] <= 890
fil = fil1 & fil2
df[fil]

           text    color  size  position  time        sn        userid
71            呀  #FFFFFF     1         0   100  42386189   UwUsb924549
72           二刷  #FFFFFF     1         0   101  43860125  inspiration9
73            簽  #FFFFFF     1         0   105  40784961  yu2501171025
74          羊粑粑  #FFFFFF     1         0   105  44235094       K941119
75          ！！！  #FFFFFF     2         0   106  42505502  pink20111129
..          ...      ...   ...       ...   ...       ...           ...
519         小八💗  #FFFFFF     1         0   874  43182188  yinqiancai02
520     泡泡驗超市和看  #FFFFFF     1         0   876  44179856    g840483938
521         ZMB  #FFFFFF     1         0   877  42527612       ZED8090
522  體感一秒鐘提敢一秒鐘  #FFFFFF     1         0   889  45729097        Mia130
523     兄弟有事請轉身  #FFFFFF     1         0   890  44754781      D0690422

[453 rows x 7 columns]



```
Everything is an object
任何東西都有形態, 每種型態都有自己的操作

list   [0]  for...in .append

以前: print(3.14)
現在: 功能(不加小括號)是一種型態
print: 刷牙步驟      (3.14): 操作得到結果

```

In [28]:
import random
b = int
b(4.6)
def func(mode=0):
    if mode == 0:
        return random.randint
    else:
        return random.uniform

func(1)(6, 7)

6.90947225215546

In [43]:
def func(s):
    s_int = int(s)
    s_int_r = round(s_int / 10.0)
    minute = s_int_r // 60
    seconds = s_int_r % 60
    return "{:02d}:{:02d}".format(minute, seconds)

# func(876)
df["time_conv"] = df["time"].apply(func)
df

,text,color,size,position,time,sn,userid,time_conv
0,二刷,#FFFFFF,1,0,0,42903755,qaz1210731,00:00
1,吉伊卡哇！,#FFFFFF,1,0,0,45641971,dodylee0107,00:00
2,感謝動畫瘋！,#FFFFFF,1,0,0,45796240,hyg125,00:00
3,2025.11.24簽,#FDE53D,1,0,0,47316552,MilkTea157,00:00
4,吉依好可愛,#FFFFFF,1,0,5,40580321,KingOrange69,00:00
...,...,...,...,...,...,...,...,...
524,ˊˊˊˊˊˊˊˊˊˊˊˊˊˊˊˊˊˊˊ,#FFFFFF,1,0,893,46704569,swyan,01:29
525,我,#FFFFFF,1,0,897,45779317,Webb2012,01:30
526,😀,#00C3FC,1,0,898,40894473,kekerry75,01:30
527,沒了？？？？,#FFFFFF,1,0,901,42188563,linzzi,01:30
528,哈,#FF0026,1,0,901,44529579,st5109185,01:30

In [39]:
"{}".format(str(1).zfill(4))
"{:04d}".format(1)

'   1'



```
簡單nlp(自然語言處理)
jieba

TF-IDF: 抓重點
1. 次數(TF): 多, 重要程度高
2. 常見度(IDF): 高, 低
重要性 = 次數 * 1/常用度

```

In [45]:
import jieba
import urllib.request as req

url = "https://github.com/fxsjy/jieba/raw/master/extra_dict/dict.txt.big"
req.urlretrieve(url, "big")
jieba.set_dictionary("big")

In [50]:
import jieba.analyse
s = "台灣最大入口網站，Yahoo奇摩新聞提供跨平台、即時、多元、專業的最新時事動態，讓你隨時隨地瀏覽最新新聞"
jieba.analyse.extract_tags(s)
jieba.add_word("吉伊卡哇")

In [51]:
def func(s):
    tags = jieba.analyse.extract_tags(s)
    return str(tags)

df["text"].apply(func)

0                 ['二刷']
1               ['吉伊卡哇']
2           ['感謝', '動畫']
3      ['2025.11', '24']
4          ['吉依好', '可愛']
             ...
524                   []
525                   []
526                   []
527                   []
528                   []
Name: text, Length: 529, dtype: object

In [ ]:
# python sqlite
# python with sql
import sqlalchemy
from sqlalchemy import create_engine
from sqlalchemy import Table, Column, Integer, String, MetaData, ForeignKey
from sqlalchemy import inspect
from sqlalchemy.sql import text


metadata = MetaData()
books = Table('book', metadata,
  Column('id', Integer, primary_key=True),
  Column('title', String),
  Column('primary_author', String),
)

engine = create_engine('sqlite:///bookstore.db')
metadata.create_all(engine)

# insert
with engine.connect() as connection:
    title = "Best Journey"
    primary_author = "Elwing"

    statement = text("""INSERT INTO book(title, primary_author) VALUES(:title, :primary_author)""")

    connection.execute(statement.params(title=title, primary_author=primary_author))
    connection.commit()

    result = connection.execute(text('SELECT * FROM book'))
    for row in result:
        print(row)